### ISSUE TITLE
Missing 40x40 square flags

### ISSUE THREAD

**Issue by danieltmbr** [transferwise/neptune#11]
I exported the 40x40 square flags from Figma Neptune Foundation, but 3 of the Balance currencies are missing their square flag:
- Botswana Pula (BWP)
- Uruguayan Peso (UYU)
- Vietnamese Dong (VND)

**Comment by christie-tw** [comment]
We also need: 
- Bahrain (BHD)
- Costa Rica (CRC)
- Kuwait (KWD)
- Mauritius (MUR)
- Monambique (MZN)
- Nambia (NAD)
- Oman (OMR)
- Qatar (QAR)
- Uruguay (UYU)
- Zambia (ZMW)

This is what we are using at the moment and it's not wonderful :) Would be good to get all sizes added to the Figma file if possible.
[svg flags.zip](https://github.com/transferwise/neptune/files/4076795/svg.flags.zip)

**Comment by anttio** [comment]
These missing flags have now beed added to the Neptune Figma library.

**Comment by christie-tw** [comment]
Hey @anttio - I can't see the flag for KWD? Is that one yet to be added?

**Comment by anttio** [comment]
@christie-tw I just added KWD to Figma library. And while at it I also added COP, JMD, ISK, SAR and TWD which were missing in some sizes.
