### ISSUE TITLE
Cross platform alerts

### ISSUE THREAD

**Issue by twlleon** [transferwise/neptune#13]
The main concern: 
We don't have a proper shared way of approaching alerts (errors or informational) cross platform, plus the ones we currently have aren't taking into consideration some limitations and UX considerations we have for the (Send money) calculator. There's also a case to be made for alerts and error components needing to be similar - they tend to work hand-in-hand.

So as a solution for the transfer flow calculator we've built an alert component that serves our purposes, works the same (hopefully) cross platform and seems to work well in other places it's been used at. But we're aware that introducing more components isn't the way to go, rather we need structure to understand when to use what and what is the component that serves all of our alert needs. 
[Context for what we did and why we did it + some versions of alerts that are live ](https://www.figma.com/file/c03P4jxwhw1bVgLCQDm5ry/Transfer-Flow-components?node-id=152%3A721)

Solutions: 
As a start, I'd like to keep the way we approach alerts/errors in the calculator as a source of truth for the calculator. If you consider that this component is suitable for the design system, I'd like to map it out properly and create documentation for it. 
Next I'd like to gain more insights from the Design Systems team and whomever is interested to figure out what is an error/alert design that works cross platform, what limitations we need to consider and what do we need to do to get that implemented.

**Comment by gusso** [comment]
Thanks @twlleon, we'll start looking into how we standardise fields on mobile soon and will bring the error aspects into it, then it should be easier to bring the solution everywhere.

**Comment by anttio** [comment]
Closing this and moving to JIRA.
