### ISSUE TITLE
When should a pay button be used? 

### ISSUE THREAD

**Issue by giljulio** [transferwise/neptune#17]
The current definition is "Use at the start and end of a payment flow". What is the definition for a payment flow? Balance actions currently don't use the pay buttons in the balance screen.

https://github.com/transferwise/neptune/blame/master/components/button.md#L24

Proposal: Rename to confirmation button and only use them at the final step of a flow (when the action is irreversible). This would mean that the send button in the navigation should be changed to the accent colour (mid blue).

**Comment by anttio** [comment]
Closing this and moving to JIRA.
