### ISSUE TITLE
Images in radio cells

### ISSUE THREAD

**Issue by eddiewoodleytw** [transferwise/neptune#19]
Some use cases require images to be shown in radio cells in the same way that they are shown in option cells, but this is not currently shown in Figma.

Example:

<img width="415" alt="Screenshot 2020-01-29 at 10 51 41" src="https://user-images.githubusercontent.com/58181045/73350691-6f15ba80-4285-11ea-9274-0a4ca5ff44a4.png">

**Comment by gusso** [comment]
Thanks @eddiewoodleytw, we're waiting on a tool upgrade that will give us a bit more control on how we create flexible components on Figma, I'll update this when we move forward.
