### ISSUE TITLE
What's the loading pattern?

### ISSUE THREAD

**Issue by giljulio** [transferwise/neptune#2]
On android we've various types of loading types:

For example:
- Shimmer
- Full screen loader (borderless Lottie icon)
- Bar loader for when content is on screen
- Pull to refresh loader

It has been documented [here](https://github.com/transferwise/transferwise-android/wiki/Loading,-Empty,-Data,-Error-behaviour) from an android perspective but would be good to have some alignment and guidance

**Comment by gusso** [comment]
Did a quick review of these with @aftabahmadTW just now and they all seem valid to me.

One option we have to increase context for the loaders is removing the bar loader, and including more contextual loaders. This contextual loader would potentially use the same animated asset we use on the full screen loader and on the pull to refresh one, unifying how we present loading states by the same visual cue. Some examples would be:

- when freezing the card, the circular button would show a loader element inside the circle while the data is loading
- when searching a list and waiting for results, the content would be replaced with shimmered versions of the results

Does this sound reasonable? Do you think we'd lose something?

From what I searched on the apps, the instances where Android displays the bar loader, iOS simply makes the tapped component inactive until the action is done. @danieltmbr do you have thoughts?
