### ISSUE TITLE
Let's kill placeholder text. It's bad for accessibility.

### ISSUE THREAD

**Issue by StephanieTW** [transferwise/neptune#20]
Hey @mrmurtz and I are working on some designs, and the topic of placeholder text came up. Turns out it's not great for accessibility, and it would be great if we could stop using it in our designs. Maybe remove it from our design system. Thoughts?

**TLDR:**
Quick bit of Googling shows we prolly shouldn't use placeholder text at all. (Unless we have a really good reason — and I can't think of one.) It's bad for accessibility, and bad for comprehension.

**Slightly longer explanation:**

- Not all screen readers and browsers support this attribute. If it's not read by a screen reader, the user won't get the info.

- Google doesn't automatically translate placeholder text, so people who speak other languages might not be able to read it.

- It's a cognitive burden for all users, especially those with cognitive and motor impairments. It strains your memory as it disappears as you type. It's also easy to miss the form field because you might think it's already been filled in.

**Solution:**
Use field label to do most of the work.
If you need to add a hint, it’s best to place that text outside the field so that it is always visible.

**Some extra reading if you're interested**
https://www.nngroup.com/articles/form-design-placeholders/
https://uxdesign.cc/alternatives-to-placeholder-text-13f430abc56f
https://www.smashingmagazine.com/2018/06/placeholder-attribute/
https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/ (edited)

**Comment by mrmurtz** [comment]
Quick mock up if we moved the placeholder to place it between the label and field. 

![image](https://user-images.githubusercontent.com/12968900/73356444-4b0ca600-4292-11ea-9b55-749f91d03045.png)

How it looks in a form for e.g. 

![image](https://user-images.githubusercontent.com/12968900/73356486-64155700-4292-11ea-95b9-153c55e788d6.png)

**Comment by giljulio** [comment]
> It's a cognitive burden for all users, especially those with cognitive and motor impairments. It strains your memory as it disappears as you type. It's also easy to miss the form field because you might think it's already been filled in.

Web could follow mobile, when the user focuses on the field the label moves so it's always visible. Like so:

<img src="https://user-images.githubusercontent.com/2804050/73443741-2aeeec80-434f-11ea-8e97-a8af2dea4389.png" width="200" />

As for some screen readers not picking it up - seems strange to me because this is a standard attribute in the `input` tag https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text

**Comment by anttio** [comment]
Closing this for now. Input audits happening and tracked in JIRA.
