### ISSUE TITLE
Add a new mobile web navigation

### ISSUE THREAD

**Issue by StevePole** [transferwise/neptune#21]
We would like to make mobile web follow the approach of the mobile apps as closely as possible.  To do so, we need an equivalent of the mobile nav:
![image](https://user-images.githubusercontent.com/1318111/73447884-90df7200-4357-11ea-8829-a0ed910989e7.png)

This needs to be customisable to show different icons & links for different users.  As multi-user access allows view-only users with less capabilities, we should facilitate several modes:

- 4 links and 1 CTA
- 2 links and 1 CTA
- 2 links, no CTA
- 3 links, no CTA
- 4 links, no CTA

The component needs to be responsive.  On wider screens, we should set a maximum width for the links and extend an empty bar to fill the rest of screen on both sides.  The links and CTA should remain central.

*Multiple CTAs*
For the first version this is not required, but ultimately we'll likely want to open a popover when the user clicks the CTA button with multiple options available.  For that reason I would design this in such a way that components expects an array of CTAs from the start.  For now, the implementation can just use the first one.

**Comment by sergonius** [comment]
Something to think about is that in web we also have the little help bubble:
![help](https://user-images.githubusercontent.com/6144993/73631037-714e8f00-4660-11ea-869c-3df98aa70dbe.png)

**Comment by gusso** [comment]
@StevePole Is this confirmed that should be built?

@pixeljunkies Have you considered what @sergonius mentioned regarding the help bubble? Should we move it to float above the tab bar? I'm afraid it's gonna look even more like a FAB.

**Comment by anttio** [comment]
Closing this in favour of JIRA issue.
