### ISSUE TITLE
Simple bullet list style

### ISSUE THREAD

**Issue by mrmurtz** [transferwise/neptune#23]
Our current instruction components always make use of an icon, do we have a simple bullet list that can be used in instances where a list does not need numbers or icons. 

E.g. in a flow where information is required in no particular order but needs to be broken down point by point for better comprehension. 

![image](https://user-images.githubusercontent.com/12968900/73659269-cead0500-468d-11ea-851e-54d6b7beb4e0.png)

**Comment by StevePole** [comment]
We already have HTML styles for bulleted lists, not sure this needs to be a component?

Your spacing looks a little larger than the current implementation.

**Comment by gusso** [comment]
@mrmurtz Let us know if you're able to reproduce the native web's bullets on Figma, if so you can close the ticket.

**Comment by gusso** [comment]
Sorted, we're using inline glyphs (•) in Figma.
