### ISSUE TITLE
Play video buttons inconsistent on web

### ISSUE THREAD

**Issue by meylinbayr** [transferwise/neptune#24]
![Audit - 3](https://user-images.githubusercontent.com/59610895/73669128-db862480-469e-11ea-8799-6f55e959c6be.png)

We have 3 variations of play buttons outlined in the example image attached. 
Play buttons inconsistency on web in the following places (didnt audit the whole product so there might be more):
1. Business page
2. Balances page
3. Landing page

**Why we are looking into this?** 
We wanted to improve the experience on empty states in Balances. Currently we have a video served on the empty state of Balances, however it is not inline with the rest of our content. We want to create bespoke component for video placeholders, thus looking in patterns from our existing solutions. 
 
![image](https://user-images.githubusercontent.com/59610895/73669638-b0e89b80-469f-11ea-9471-386b7689cb7b.png)

Suggestion, can we align button and video styles. I think the option on the Landing page is very good and we would like to use something similar in the empty state of Balances. IMO we should get rid of the rounded button all together, its not inline with our styles.

**Comment by anttio** [comment]
Closing this. Addressing this issue while doing button audit.
