### ISSUE TITLE
[WEB] 4px corner radius on Bank details card on 

### ISSUE THREAD

**Issue by meylinbayr** [transferwise/neptune#28]
![Desktop 2 1](https://user-images.githubusercontent.com/59610895/74175953-b198a900-4c2e-11ea-915b-e6cad2eecf01.png)

Can we add a 4px corner radius to the Bank details card. Both expanded and non-expanded

**Comment by gusso** [comment]
We currently use 3px on most components, why does this component need the differentiation?

**Comment by meylinbayr** [comment]
3px is fine by me, I have seen a mix of corner radius in Figma, so thought 4 is the way to go. As long as this component has corner radius (which at the moment it doesnt), the receive team is fine with it. 

Also side not, but why 3? We are working in 8p grid, 3 is a strange number to use (unless we are following a Fibonacci sequence?)

**Comment by gusso** [comment]
Not sure the historical reasons, but I did another check and most web components on Figma seem to be 3.

Agree I don't see a clear reason for the number, but it seems best to keep to what we have and reconsider them all after.

**Comment by meylinbayr** [comment]
Cool consider that a 3px component than please and ignore the image :) 👍
