### ISSUE TITLE
Upload component inconsistency

### ISSUE THREAD

**Issue by AbeBialy** [transferwise/neptune#29]
Component not consistent across Neptune and React. 

What is different? 
Neptune: Title on component
React: No title

After asking Gusso:
- The correct one is on "React components"

**Comment by gusso** [comment]
@andreapiras This is what it looks like on Figma. Do you remember if the Upload component used to have a title prop, or do you think the bold text was always custom?
<img width="397" alt="Screenshot 2020-02-11 at 3 24 20 pm" src="https://user-images.githubusercontent.com/782754/74250496-98513480-4ce2-11ea-85e9-6452eb91d338.png">

**Comment by gusso** [comment]
@AbeBialy It's possible to do both. The title is optional, so feel free to not have one.

**Comment by AbeBialy** [comment]
Thanks Gusso
