### ISSUE TITLE
Native carousel missing

### ISSUE THREAD

**Issue by AbeBialy** [transferwise/neptune#30]
I don't think we have a native carousel component on "Neptune Mobile" 

Mike Twigg has one designed for the new intro screen. Should we be using this whenever needed? and are we going to include it in Neptune?

![Screenshot 2020-02-12 at 09 42 09](https://user-images.githubusercontent.com/60740790/74322602-14e42180-4d7c-11ea-8813-9d80ab006f1a.png)

**Comment by anttio** [comment]
Closing this for now. We have a JIRA ticket for carousel.
