### ISSUE TITLE
iOS: Modality VS Full Screen 

### ISSUE THREAD

**Issue by nicoloarena1102** [transferwise/neptune#32]
The way we use modality in the iOS app isn't aligned with the Apple Human Interface Guidelines.

_Create a modal experience only when it's critical to focus people's attention on making a choice or performing a task that's different from their current task. A modal experience takes people out of their current context and requires an action to dismiss, so it's essential to use it only when it provides a clear benefit._

We're currently using Modality when users are entering a new area of the product and have to navigate through a high amount of information. E.g. Card management.

We also have blue success screens used inside a modal, which means the user has been undertaking an action which requires a success screen, which shouldn't be happening inside a modal.

https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/

![IMG_6945](https://user-images.githubusercontent.com/36227398/74534754-59162400-4f2c-11ea-94c1-27544955d7bf.PNG)

**Comment by anttio** [comment]
Closing this and moved to JIRA.
