### ISSUE TITLE
Web navigation inconsistencies 

### ISSUE THREAD

**Issue by nicoloarena1102** [transferwise/neptune#33]
![image](https://user-images.githubusercontent.com/36227398/74860888-53ac4580-5341-11ea-9d10-d64dd11c89dc.png)

Web navigation changes each time you click on a different tab. Teams have failed to align this individually due to lack of prioritisation for this, so it'd probably be more efficient to fix this at a system level. 

All tabs should follow the behaviour of the activity tab.

Current issues:
• balances still with the old nav bar design. takes ages to load
• card tab implemented the changes, but it's still buggy (some other tabs don't appear)
• recipient tab still with the old nav bar design. apple/google store upsells are huge and off-centred and the first thing to load

**Comment by anttio** [comment]
Closing this as it is being addressed by activity team.
