### ISSUE TITLE
Checkbox component is actually a toggle/switch

### ISSUE THREAD

**Issue by lagubull** [transferwise/neptune#35]
Hi! It seems like toggle's have been named checkbox which seems confusing as we would not be able to provide a nice UX if we were to render a selection list with view full of toggles. the purpose of that UI element is often settings menu not selection where checkboxes are indeed used.

is it possible to rename the component to avoid confusing and also to create a checkbox component?

**Comment by anttio** [comment]
Moved to JIRA.
