### ISSUE TITLE
Disabled inputs, input placeholder and form group titles are visually too similar

### ISSUE THREAD

**Issue by mikknarusk** [transferwise/neptune#7]
Every line in the form here looks almost the same, which makes it very difficult for a user to determine 
- which inputs they have to (or can) edit
- which rows are inputs, which are titles (reading top-down, my first click was on the "Address" title expecting to fill my address)

![Screenshot_20191216-095532](https://user-images.githubusercontent.com/43746750/70975337-65a80880-20b2-11ea-8df0-d35b0c14e062.jpg)

**Comment by anttio** [comment]
Closing this and moving to JIRA.
